[build]
  publish = "public"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[functions."extract"]
  timeout = 60

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
